In [10]:
import numpy as np

N = 10
pr_inf  = .1
pr_mask = .8
days = 7

A = np.zeros((N,8), dtype = np.int32)

A[:,0] = np.arange(N)
A[:,1] = 1
A[:,2] = np.random.binomial(1,pr_inf,N)
A[A[:,2]==1,1] = 0 #no longer sus bc inf

#A[:,1] = A[:,1] - A[:,2]

A[:,4] = np.random.binomial(1,pr_mask,N)

#A[:,5] = A[:,2]*days
A[A[:,2]==1,5] = 7

A[:,6] = np.random.choice(N,N,replace = False)

A[A[:,6],7] = A[:,0]

print(A)

[[0 1 0 0 1 0 3 5]
 [1 1 0 0 1 0 6 8]
 [2 1 0 0 0 0 8 3]
 [3 1 0 0 1 0 2 0]
 [4 1 0 0 1 0 4 4]
 [5 1 0 0 0 0 0 6]
 [6 1 0 0 1 0 5 1]
 [7 0 1 0 1 7 9 9]
 [8 1 0 0 1 0 1 2]
 [9 1 0 0 1 0 7 7]]
