In [64]:
import numpy as np

In [65]:
print(np.array([[5,0], [7,1]]))

[[5 0]
 [7 1]]


In [66]:
arr = np.ones(shape=(3,4),dtype = 'int8')

print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [67]:
from numpy import random
arr = random.randint(4, 9, size = (5,5))
print(arr)
print(arr[3,2])

[[4 7 7 7 7]
 [4 8 6 4 5]
 [8 6 4 4 4]
 [4 4 6 6 8]
 [7 5 4 6 6]]
6


In [74]:
arr = random.randint(1, 3, size = (5,5))
print(arr/10)
print(arr[3])
for i in arr[3]:
    print(i)

[[0.1 0.1 0.2 0.2 0.2]
 [0.2 0.1 0.2 0.1 0.2]
 [0.2 0.1 0.1 0.2 0.1]
 [0.2 0.2 0.1 0.1 0.1]
 [0.2 0.1 0.1 0.2 0.2]]
[2 2 1 1 1]
2
2
1
1
1


In [92]:
arr = np.arange(1,10)
arr = arr.reshape((3,3))
print(arr)
print(np.sum(arr))
print(np.sum(arr,0))
print(np.sum(arr,1))

print(np.mean(arr))
print(np.mean(arr,0))
print(np.mean(arr,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
5.0
[4. 5. 6.]
[2. 5. 8.]
