In [41]:
#import random
#x = random.randint
#z = list(range(1,11))
#y = random.sample(z,1)
#print(f"x is {x}")
#print(f"y is {y}")

import numpy as np

X = np.random.randint(0,10,12)
print(X)
print(type(X))
print(X.shape)
X = X.reshape(4,3)
print(X)
#X is a 2 dimentional array
# or a matrix, rows and columns
print(X[0,0])
print(X[0,1])

X3 = np.zeros((4,3,2))
print(X3)
print(X3.shape)
Y3 = np.random.randint(0,10,24)
print(Y3)
Y3 = Y3.reshape(4,3,2)
print(Y3)
print(Y3[2,0,0])
Y3[2,0,0] = 77
print("After assigning 77 to [2,0,0]")
print(Y3)
print("_"*20)
print(Y3[2])
print(Y3[2,:,:])
print("_"*20)
print(Y3[:,0,:])#first row from all dimensions

# 5 people, flip coin once
Z = np.random.binomial(1,0.5,5)
print(Z)

#1 person, flip coin 5 times
Z2 = np.random.binomial(5,0.5,1)
print(Z2)

# 4 people, flip coin ten times 
#coin has 20% chance of 1, 80 % chance of 0
Z3 = np.random.binomial(10,0.2,4)
print(Z3)

A = np.random.multinomial(1,[0.5,0.3,0.2],10)
print(A)

[3 2 4 3 2 6 3 1 7 2 6 8]
<class 'numpy.ndarray'>
(12,)
[[3 2 4]
 [3 2 6]
 [3 1 7]
 [2 6 8]]
3
2
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
(4, 3, 2)
[4 8 8 1 3 9 5 9 2 9 3 6 3 0 5 0 3 3 3 6 2 9 2 1]
[[[4 8]
  [8 1]
  [3 9]]

 [[5 9]
  [2 9]
  [3 6]]

 [[3 0]
  [5 0]
  [3 3]]

 [[3 6]
  [2 9]
  [2 1]]]
3
After assigning 77 to [2,0,0]
[[[ 4  8]
  [ 8  1]
  [ 3  9]]

 [[ 5  9]
  [ 2  9]
  [ 3  6]]

 [[77  0]
  [ 5  0]
  [ 3  3]]

 [[ 3  6]
  [ 2  9]
  [ 2  1]]]
____________________
[[77  0]
 [ 5  0]
 [ 3  3]]
[[77  0]
 [ 5  0]
 [ 3  3]]
____________________
[[ 4  8]
 [ 5  9]
 [77  0]
 [ 3  6]]
[1 1 1 1 1]
[0]
[2 2 2 2]
[[0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]]
