In [155]:
import numpy as np
N = 20
# Column   Meaning
# 0        Row number
# 1        Suseptible
# 2        Infected
# 3        Recovered
# 4        Masked
# 5        Num days sick (for infected only)
# 6        Who did you visit
# 7        Who visited you


print("Step 1")
A = np.zeros([N,8], dtype = np.int32)

print("Step 2")
A[:,0] = np.arange(N)

print("Step 3")
A[:,1] = 1

print("Step 4")
#print(A)
A[:,2] = np.random.binomial(1,.1, N)
print(A)

print("Step 5")
A[:,1] = A[:,1] - A[:,2]
print(A)


Step 1
Step 2
Step 3
Step 4
[[ 0  1  0  0  0  0  0  0]
 [ 1  1  0  0  0  0  0  0]
 [ 2  1  0  0  0  0  0  0]
 [ 3  1  0  0  0  0  0  0]
 [ 4  1  0  0  0  0  0  0]
 [ 5  1  0  0  0  0  0  0]
 [ 6  1  0  0  0  0  0  0]
 [ 7  1  0  0  0  0  0  0]
 [ 8  1  0  0  0  0  0  0]
 [ 9  1  0  0  0  0  0  0]
 [10  1  0  0  0  0  0  0]
 [11  1  0  0  0  0  0  0]
 [12  1  0  0  0  0  0  0]
 [13  1  0  0  0  0  0  0]
 [14  1  0  0  0  0  0  0]
 [15  1  0  0  0  0  0  0]
 [16  1  0  0  0  0  0  0]
 [17  1  0  0  0  0  0  0]
 [18  1  0  0  0  0  0  0]
 [19  1  0  0  0  0  0  0]]
Step 5
[[ 0  1  0  0  0  0  0  0]
 [ 1  1  0  0  0  0  0  0]
 [ 2  1  0  0  0  0  0  0]
 [ 3  1  0  0  0  0  0  0]
 [ 4  1  0  0  0  0  0  0]
 [ 5  1  0  0  0  0  0  0]
 [ 6  1  0  0  0  0  0  0]
 [ 7  1  0  0  0  0  0  0]
 [ 8  1  0  0  0  0  0  0]
 [ 9  1  0  0  0  0  0  0]
 [10  1  0  0  0  0  0  0]
 [11  1  0  0  0  0  0  0]
 [12  1  0  0  0  0  0  0]
 [13  1  0  0  0  0  0  0]
 [14  1  0  0  0  0  0  0]
 [15  1  0  0  0  0

In [156]:
print("Step 6")
A[:,3] = 0
A[:,4] = np.random.binomial(1,.8,N)
print(A)

print("Step 7")
A[:,5] = 7*A[:,2]
print(A)

print("Step 8")
A[:,6] = np.random.choice(A[:,0],N, replace = False)
print(A)

print("Step 9")
B = np.transpose(np.concatenate((A[:,0], A[:,6]),axis = 0).reshape(2,N))
C = B[B[:,1].argsort()]
A[:,7] = C[:,0]
print(A)


Step 6
[[ 0  1  0  0  1  0  0  0]
 [ 1  1  0  0  1  0  0  0]
 [ 2  1  0  0  0  0  0  0]
 [ 3  1  0  0  1  0  0  0]
 [ 4  1  0  0  1  0  0  0]
 [ 5  1  0  0  1  0  0  0]
 [ 6  1  0  0  1  0  0  0]
 [ 7  1  0  0  1  0  0  0]
 [ 8  1  0  0  1  0  0  0]
 [ 9  1  0  0  1  0  0  0]
 [10  1  0  0  0  0  0  0]
 [11  1  0  0  0  0  0  0]
 [12  1  0  0  1  0  0  0]
 [13  1  0  0  1  0  0  0]
 [14  1  0  0  0  0  0  0]
 [15  1  0  0  1  0  0  0]
 [16  1  0  0  1  0  0  0]
 [17  1  0  0  1  0  0  0]
 [18  1  0  0  1  0  0  0]
 [19  1  0  0  1  0  0  0]]
Step 7
[[ 0  1  0  0  1  0  0  0]
 [ 1  1  0  0  1  0  0  0]
 [ 2  1  0  0  0  0  0  0]
 [ 3  1  0  0  1  0  0  0]
 [ 4  1  0  0  1  0  0  0]
 [ 5  1  0  0  1  0  0  0]
 [ 6  1  0  0  1  0  0  0]
 [ 7  1  0  0  1  0  0  0]
 [ 8  1  0  0  1  0  0  0]
 [ 9  1  0  0  1  0  0  0]
 [10  1  0  0  0  0  0  0]
 [11  1  0  0  0  0  0  0]
 [12  1  0  0  1  0  0  0]
 [13  1  0  0  1  0  0  0]
 [14  1  0  0  0  0  0  0]
 [15  1  0  0  1  0  0  0]
 [16  1  0  0